{
 "title": "Cluster compute resources overview",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Cluster overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pods scheduled",
   "type": "stat",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_status_phase{phase=~\"Running|Pending\"} == 1)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Nodes types",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 10, "x": 4, "y": 1 },
   "targets": [
    {
     "expr": "sum by (label_eks_amazonaws_com_capacity_type) (kube_node_labels)",
     "legendFormat": "{{label_eks_amazonaws_com_capacity_type}}"
    }
   ]
  },
  {
   "title": "Node groups",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 1 },
   "targets": [
    {
     "expr": "sum by (label_intent) (kube_node_labels)",
     "legendFormat": "{{label_eks_amazonaws_com_capacity_type}}"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{container_name!=\"POD\", image!=\"\"})",
     "legendFormat": "Utilization"
    },
    {
     "expr": "(sum (kube_node_status_allocatable{resource=\"memory\"}) by ())",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(sum (kube_pod_container_resource_limits{resource=\"memory\"}) by (pod) * on (pod) group_right () (kube_pod_status_phase{phase=~\"Running|Pending\"} == 1))",
     "legendFormat": "Limits"
    },
    {
     "expr": "sum(sum (kube_pod_container_resource_requests{resource=\"memory\"}) by (pod) * on (pod) group_right () (kube_pod_status_phase{phase=~\"Running|Pending\"} == 1))",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum (rate(node_cpu_seconds_total{mode!=\"idle\"}[5m]))",
     "legendFormat": "Utilization"
    },
    {
     "expr": "(sum (kube_node_status_allocatable{resource=\"cpu\"}) by ())",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(sum (kube_pod_container_resource_limits{resource=\"cpu\"}) by (pod) * on (pod) group_right () (kube_pod_status_phase{phase=~\"Running|Pending\"} == 1))",
     "legendFormat": "Limits"
    },
    {
     "expr": "sum(sum (kube_pod_container_resource_requests{resource=\"cpu\"}) by (pod) * on (pod) group_right () (kube_pod_status_phase{phase=~\"Running|Pending\"} == 1))",
     "legendFormat": "Requests"
    }
   ]
  },
  { "title": "RAM / Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "RAM requests",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum (sum (kube_pod_container_resource_requests{resource=\"memory\"}) by (pod) * on (pod) group_right () (kube_pod_status_phase{phase=~\"Running|Pending\"} == 1) * on (pod) group_right kube_pod_info) by (node)) / on (node) (sum (kube_node_status_allocatable{resource=\"memory\"}) by (node))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM limits",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum (sum (kube_pod_container_resource_limits{resource=\"memory\"}) by (pod) * on (pod) group_right () (kube_pod_status_phase{phase=~\"Running|Pending\"} == 1) * on (pod) group_right kube_pod_info) by (node)) / on (node) (sum (kube_node_status_allocatable{resource=\"memory\"}) by (node))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM utilization",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum (sum (container_memory_working_set_bytes{container_name!=\"POD\", image!=\"\"}) by (pod) * on (pod) group_right () (kube_pod_status_phase{phase=~\"Running|Pending\"} == 1) * on (pod) group_right kube_pod_info) by (node)) / on (node) (sum (kube_node_status_allocatable{resource=\"memory\"}) by (node))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "CPU / Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "CPU utilization",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(sum (rate(node_cpu_seconds_total{mode!=\"idle\"}[5m])) by (instance), \"internal_ip\", \"$1\", \"instance\", \"(.*):.*\") * on (internal_ip) group_right kube_node_info / on (node) sum (kube_node_status_allocatable{resource=\"cpu\"}) by (node)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU limits",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum (sum (kube_pod_container_resource_limits{resource=\"cpu\"}) by (pod) * on (pod) group_right () (kube_pod_status_phase{phase=~\"Running|Pending\"} == 1) * on (pod) group_right kube_pod_info) by (node)) / on (node) (sum (kube_node_status_allocatable{resource=\"cpu\"}) by (node))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU requests",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum (sum (kube_pod_container_resource_requests{resource=\"cpu\"}) by (pod) * on (pod) group_right () (kube_pod_status_phase{phase=~\"Running|Pending\"} == 1) * on (pod) group_right kube_pod_info) by (node)) / on (node) (sum (kube_node_status_allocatable{resource=\"cpu\"}) by (node))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Hidden",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "collapsed": true,
   "panels": [
    {
     "title": "Node resources",
     "type": "barchart",
     "gridPos": { "h": 23, "w": 24, "x": 0, "y": 14 },
     "targets": [
      {
       "expr": "sum (sum (kube_pod_container_resource_requests{resource=\"cpu\"}) by (pod) * on (pod) group_right () (kube_pod_status_phase{phase=~\"Running|Pending\"} == 1) * on (pod) group_right kube_pod_info) by (node)",
       "legendFormat": "Requested"
      },
      {
       "expr": "sum (kube_node_status_allocatable{resource=\"cpu\"}) by (node)",
       "legendFormat": "Max"
      }
     ]
    }
   ]
  }
 ]
}